# Generated by Django 4.2.5 on 2023-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cv",
            old_name="experience",
            new_name="about_me",
        ),
        migrations.RenameField(
            model_name="cv",
            old_name="summary",
            new_name="skills",
        ),
        migrations.AddField(
            model_name="cv",
            name="work_experience",
            field=models.TextField(default="hahah"),
            preserve_default=False,
        ),
    ]
