# Generated by Django 4.2.5 on 2023-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0002_rename_experience_cv_about_me_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
    ]
