# Generated by Django 4.2.5 on 2023-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0005_alter_cv_education_alter_cv_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="social",
            field=models.URLField(blank=True, default=""),
        ),
    ]
