# Generated by Django 4.2.5 on 2023-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0006_alter_cv_social"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="social",
        ),
        migrations.AddField(
            model_name="cv",
            name="github_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="linkedin_link",
            field=models.URLField(blank=True),
        ),
    ]
